export const Countries = [
    { name: 'United States', code: 'USA' },
    { name: 'Canada', code: 'CAN' },
    { name: 'United Kingdom', code: 'GBR' },
    { name: 'Germany', code: 'DEU' },
    { name: 'France', code: 'FRA' },
    { name: 'Italy', code: 'ITA' },
    { name: 'Spain', code: 'ESP' },
    { name: 'Australia', code: 'AUS' },
    { name: 'Brazil', code: 'BRA' },
    { name: 'India', code: 'IND' },
    { name: 'China', code: 'CHN' },
    { name: 'Japan', code: 'JPN' },
    { name: 'Russia', code: 'RUS' },
    { name: 'Mexico', code: 'MEX' },
    { name: 'South Korea', code: 'KOR' },
    { name: 'Turkey', code: 'TUR' },
    { name: 'Netherlands', code: 'NLD' },
    { name: 'Saudi Arabia', code: 'SAU' },
    { name: 'Argentina', code: 'ARG' },
    { name: 'South Africa', code: 'ZAF' },
    { name: 'Sweden', code: 'SWE' },
    { name: 'Switzerland', code: 'CHE' },
    { name: 'Indonesia', code: 'IDN' },
    { name: 'Poland', code: 'POL' },
    { name: 'Belgium', code: 'BEL' },
    { name: 'Norway', code: 'NOR' },
    { name: 'Austria', code: 'AUT' },
    { name: 'Thailand', code: 'THA' },
    { name: 'United Arab Emirates', code: 'ARE' },
    { name: 'Israel', code: 'ISR' },
    { name: 'Denmark', code: 'DNK' },
    { name: 'Singapore', code: 'SGP' },
    { name: 'Malaysia', code: 'MYS' },
    { name: 'Ireland', code: 'IRL' },
    { name: 'Hong Kong', code: 'HKG' },
    { name: 'New Zealand', code: 'NZL' },
    { name: 'Philippines', code: 'PHL' },
    { name: 'Pakistan', code: 'PAK' },
    { name: 'Egypt', code: 'EGY' },
    { name: 'Finland', code: 'FIN' },
    { name: 'Portugal', code: 'PRT' },
    { name: 'Greece', code: 'GRC' },
    { name: 'Czech Republic', code: 'CZE' },
    { name: 'Romania', code: 'ROU' },
    { name: 'Hungary', code: 'HUN' },
    { name: 'Chile', code: 'CHL' },
    { name: 'Colombia', code: 'COL' },
    { name: 'Bangladesh', code: 'BGD' },
    { name: 'Vietnam', code: 'VNM' },
    { name: 'Eritrea', code: 'ERI' }, // ERI country code as requested
];
